# Generated by Django 4.2.26 on 2025-12-05 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "front",
                    models.TextField(
                        help_text="Question or prompt (front side of card)"
                    ),
                ),
                (
                    "back",
                    models.TextField(
                        help_text="Answer or response (back side of card)"
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(help_text="Next scheduled review time"),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=0, help_text="Interval in days until next review"
                    ),
                ),
                (
                    "ease_factor",
                    models.FloatField(
                        default=2.5,
                        help_text="Ease factor for SM-2 algorithm (1.3-2.5 typical range)",
                    ),
                ),
                (
                    "repetitions",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successful reviews"
                    ),
                ),
                (
                    "lapses",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of failed reviews"
                    ),
                ),
                (
                    "is_suspended",
                    models.BooleanField(
                        default=False,
                        help_text="If True, card will not appear in review sessions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="cards.deck",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
            },
        ),
    ]
