# Generated by Django 4.2.27 on 2025-12-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_back_alter_card_ease_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='generation_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
