# Generated by Django 4.2.27 on 2026-01-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_generation_meta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_deck_name_per_user'),
        ),
    ]
